swagger: "2.0"
info:
  description: Swagger file for Junit Simple Storage
  version: "1.0.0"
  title: Junit Simple Storage REST API
consumes:
  - "application/json"
produces:
  - "application/json"
basePath: "/api"
paths:
  /import:
    post:
      operationId: "rest.import_junit"
      summary: "Import JUnit file to database"
      consumes:
        - "application/xml"
      parameters:
        - name: junit
          in: body
          required: True
          schema:
            type: string
      responses:
        201:
          description: "Successfully imported"
  /health:
    get:
      operationId: "rest.health"
      summary: "Health endpoint for readiness and health probes"
      description: "Return 200 if application is running"
      responses:
        200:
          description: "Application is healthy and running"
